<!DOCTYPE html>
<html lang="ru">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Анализатор страниц</title>

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</head>

<body>

  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">

      <a class="navbar-brand" href="#">Анализатор страниц</a>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link" href="#">Главная</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Сайты</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <nav class="navbar navbar-dark bg-dark">
    <div class="container">
      <div class="col align-self-center mt-5 mb-5">

        <div class="text-light">
            <h1 class="display-3">Анализатор страниц</h1>
            <p>Бесплатно проверяйте сайты на SEO пригодность</p>
        </div>

        <div class="container-fluid p-0">
          <form class="d-flex">
            <input class="form-control me-2" type="search" placeholder="Ссылка" aria-label="Search">
            <button type="submit" class="btn btn-primary btn-lg">Проверить</button>
          </form>
        </div>

        <div class="container-fluid mt-2 p-0">
          <span class="navbar-text">
            Пример: https://www.example.com
          </span>
        </div>
      </div>
    </div>
  </nav>

</body>
</html>
